apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-smca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-smca
    app.kubernetes.io/part-of: ci10t-786-0048-app
  name: devfile-sample-smca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-smca
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-smca
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0048-tenant/ci10t-786-0048-app/devfile-sample-smca@sha256:db0fc5145ac84e143fd81fe3415e38bc991c00a1a11ac9e8a4f61511649797c4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
